### ISSUE TITLE
各種ゲージ作成

### ISSUE THREAD

**Issue by yuta0023** [UpWorks2015/SlashBrush#15]

**Comment by yuta0023** [comment]
UI配置は完了。
各種パラメータとの連携を実装していきます。

**Comment by hytkgami** [comment]
@yuta0023 
プレイヤーのHPゲージが右端まで塗りつぶされたあとにまた左端から右端にかけて塗りつぶしがはじまるのは仕様？

**Comment by yuta0023** [comment]
@hytkgami 
hpbarの問題であればこのLoopTime設定をOffにすれば止まるはずです。
画面上部の赤いゲージは敵の強攻撃のタイミングを表すゲージなので
そこは仕様です。
![screen shot 2015-12-18 at 03 37 45](https://cloud.githubusercontent.com/assets/11936751/11878395/cf51885a-a538-11e5-9c22-2449f89f665f.png)

**Comment by hytkgami** [comment]
@yuta0023 

おお、上の赤いゲージがHPかと勘違いしてた！
ありがとう理解しました！
